
INSERT INTO `Notificacion` (`idNotificacion`, `fecha`, `asunto`, `descripcion`, `estadoNotificacion`, `idUsuario`) VALUES
(260, '2019-10-14 17:03:02', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'Vista', 5),
(264, '2019-10-14 17:16:59', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(267, '2019-10-14 17:27:46', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(271, '2019-10-15 16:50:51', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(275, '2019-10-15 17:06:58', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(279, '2019-10-15 23:09:33', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(283, '2019-10-15 23:24:18', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(287, '2019-10-16 15:34:07', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(291, '2019-10-16 17:13:17', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(295, '2019-10-16 17:24:04', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(299, '2019-10-16 17:34:25', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(303, '2019-10-16 17:44:51', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(308, '2019-10-16 18:26:28', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'Vista', 5),
(312, '2019-10-16 18:36:57', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(316, '2019-10-16 18:47:20', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(320, '2019-10-16 18:57:37', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(324, '2019-10-16 19:07:48', 'Victimario Osvaldo, Daniel ilocalizable', 'El victimario Osvaldo, Daniel está ilocalizable. Por favor Verifique las incidencias de la restriccion: Osvaldo, Daniel - Villafañe, Claudia', 'NoVista', 5),
(1016, '2019-11-25 17:09:25', 'Nueva prueba de Vida', '', 'NoVista', 5),
(1017, '2019-11-25 17:16:55', 'Nueva prueba de Vida', 'levantar dos dedos', 'NoVista', 5),
(1018, '2019-11-25 17:25:46', 'Nueva prueba de Vida', 'levantar cuatro dedos', 'NoVista', 5),
(1019, '2019-11-25 21:41:04', 'Nueva prueba de Vida', 'Guiñar ojo derecho', 'NoVista', 5),
(1020, '2019-11-26 23:46:46', 'Nueva prueba de Vida', 'levantar 3 dedos', 'Vista', 2),
(1021, '2019-11-27 16:17:38', 'Fallo en prueba de vida de Maradon, Diego Armanda', 'Fallo en prueba de vida. Por favor Verifique las incidencias de la restriccion: Maradon, Diego Armanda - Villafañe, Claudia', 'Vista', 5),
(1022, '2019-11-27 17:04:51', 'Fallo en prueba de vida de Maradon, Diego Armanda', 'Fallo en prueba de vida. Por favor Verifique las incidencias de la restriccion: Maradon, Diego Armanda - Villafañe, Claudia', 'Archivada', 5),
(1023, '2021-01-16 20:09:56', 'Nueva prueba de Vida', 'Tocarse el pelo con el dedo índice', 'NoVista', 7),
(1024, '2021-01-16 20:26:58', 'Fallo en prueba de vida de Agresor2, Agresor2', 'Fallo en prueba de vida. Por favor Verifique las incidencias de la restriccion: Agresor2, Agresor2 - Victima1, Victima1', 'Vista', 5),
(1025, '2021-01-16 20:27:36', 'Nueva prueba de Vida', 'Hacer OK con la mano', 'NoVista', 7),
(1026, '2021-01-16 20:29:59', 'Nueva prueba de Vida', 'Tocarse la oreja con el pulgar', 'NoVista', 7),
(1027, '2021-01-16 20:31:03', 'Nueva prueba de Vida', 'Hacer OK con la mano', 'NoVista', 21),
(1028, '2021-01-30 20:50:36', 'Fallo en prueba de vida de Agresor1, Agresor1', 'Fallo en prueba de vida. Por favor Verifique las incidencias de la restriccion: Agresor1, Agresor1 - Victima1, Victima1', 'Vista', 20),
(1029, '2021-02-01 18:10:41', 'Fallo en prueba de vida de Agresor1, Agresor1', 'Fallo en prueba de vida. Por favor Verifique las incidencias de la restriccion: Agresor1, Agresor1 - Victima1, Victima1', 'NoVista', 20);

